Added .buildconf support (#12)
* Added .buildconf support

* Fixed commit-message, added space.yaml checks

diff --git a/.github/workflows/malevich-ci__dev.yml b/.github/workflows/malevich-ci__dev.yml
--- a/.github/workflows/malevich-ci__dev.yml
+++ b/.github/workflows/malevich-ci__dev.yml
@@ -80,8 +80,17 @@ jobs:
           name=$(basename $dir)
             if [[ $dir != *.* ]] && [[ -e $dir ]] && [[ -f $dir/Dockerfile ]];
           then
+            build_context=$dir
+            build_file=$dir/Dockerfile
+            if [[ -f $dir/.buildconf ]];
+            then
+              build_context=$( cat $dir/.buildconf | grep "BuildContext" || echo "context ${build_context}" )
+              build_context=$( echo $build_context | cut -d ' ' -f2 )
+              build_file=$( cat $dir/.buildconf | grep "BuildFile" || echo "file ${build_file}" )
+              build_file=$( echo $build_file | cut -d ' ' -f2 )
+            fi
             echo "Building ${name}"
-            docker build -q -t $image_url/$name:$commit_sha $dir || { echo "::warning::Failed to build ${name}" ; errors+=("${name}") ; continue ;}
+            docker build -q -t $image_url/$name:$commit_sha -f $build_file $build_context || { echo "::warning::Failed to build ${name}" ; errors+=("${name}") ; continue ;}
             if [[ ${{ secrets.REGISTRY_TYPE}} == ecr* ]];
             then
               echo "Finding/Creating AWS repository"
@@ -97,7 +106,7 @@ jobs:
             echo "Pushing ${name}"
             docker push -q --all-tags $image_url/$name || { echo "::warning::Failed to push ${name}" ; errors+=("${name}") ; continue ;}
             
-            if [[ -f .github/workflows/app.py ]];
+            if [[ -f .github/workflows/app.py ]] && [[ -f $dir/space.yaml ]];
             then
               python3 .github/workflows/app.py --path "lib/src/${name}/space.yaml" --url "$image_url/$name:$commit_sha"
             else
@@ -108,16 +117,18 @@ jobs:
             if [[ ${{ secrets.IMAGE_USERNAME }} == "$(cat USERNAME)" ]] && [[ ${{ secrets.IMAGE_PASSWORD}} == "$(cat PASSWORD)" ]];
             then
               echo "with credentials"
+              echo "::debug::Commit Message: $(git log --format=%B -1 $commit_sha)"
               space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
-              $commit_sha "$(echo $commit_sha | git log --format=%B -n 1)" done \
+              $commit_sha "$(git log --format=%B -1 $commit_sha)" done \
               $image_url/$name:$commit_sha \
               --image-user=$(cat USERNAME) --image-token=$(cat PASSWORD) \
               --space-username=${{ secrets.SPACE_USERNAME }} --space-password=${{ secrets.SPACE_PASSWORD }} --space-org=${{ secrets.ORG_ID }} \
               ${{ secrets.API_URL }} || { echo "::warning::Failed to report" ; errors+=("${name}") ;}
             else
               echo "without credentials"
+              echo "::debug::Commit Message: $(git log --format=%B -1 $commit_sha)"
               space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
-              $commit_sha "$(git rev-parse HEAD)" done \
+              $commit_sha "$(git log --format=%B -1 $commit_sha)" done \
               $image_url/$name:$commit_sha \
               --space-username=${{ secrets.SPACE_USERNAME }} --space-password=${{ secrets.SPACE_PASSWORD }} --space-org=${{ secrets.ORG_ID }} \
               ${{ secrets.API_URL }} || { echo "::warning::Failed to report ${name}" ; errors+=("${name}") ;}
diff --git a/.github/workflows/malevich-ci__manual.yml b/.github/workflows/malevich-ci__manual.yml
--- a/.github/workflows/malevich-ci__manual.yml
+++ b/.github/workflows/malevich-ci__manual.yml
@@ -8,7 +8,7 @@ on:
       build:
         description: 'Build images'
         required: false
-        default: true
+        default: 'true'
         type: choice
         options:
         - true
@@ -89,8 +89,17 @@ jobs:
             name=$(basename $dir)
             if [[ $dir != *.* ]] && [[ -e $dir ]] && [[ -f $dir/Dockerfile ]]; 
             then
+              build_context=$dir
+              build_file=$dir/Dockerfile
+              if [[ -f $dir/.buildconf ]];
+              then
+                build_context=$( cat $dir/.buildconf | grep "BuildContext" || echo "context ${build_context}" )
+                build_context=$( echo $build_context | cut -d ' ' -f2 )
+                build_file=$( cat $dir/.buildconf | grep "BuildFile" || echo "file ${build_file}" )
+                build_file=$( echo $build_file | cut -d ' ' -f2 )
+              fi
               echo "Building ${name}"
-              docker build -q -t $image_url/$name:$commit_sha $dir || { echo "::warning::Failed to build ${name}" ; errors+=("${name}") ; continue ;}
+              docker build -q -t $image_url/$name:$commit_sha -f $build_file $build_context || { echo "::warning::Failed to build ${name}" ; errors+=("${name}") ; continue ;}
               if [[ ${{ secrets.REGISTRY_TYPE}} == ecr* ]]; 
               then
                 echo "Finding/Creating AWS repository"
@@ -105,10 +114,12 @@ jobs:
               fi  
               echo "Pushing ${name} "
               docker push -q --all-tags $image_url/$name || { echo "::warning::Failed to push ${name}" ; errors+=("${name}") ; continue ;}
-              if [[ -f .github/workflows/app.py ]]; 
+              if [[ -f .github/workflows/app.py ]] && [[ -f $dir/space.yaml ]];  
               then
                 python3 .github/workflows/app.py --path "lib/src/${name}/space.yaml" --url "$image_url/$name:$commit_sha" && \
                 echo "::notice::${name} configured"
+              else
+                echo "::warning::${name} has no space.yaml"
               fi
 
               echo -n "Testing ${name} "  
@@ -116,7 +127,7 @@ jobs:
               then
                 echo "with credentials"
                 space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
-                $commit_sha "$(echo $commit_sha | git log --format=%B -n 1)" done \
+                $commit_sha "$(git log --format=%B -1 $commit_sha)" done \
                 $image_url/$name:$commit_sha \
                 --image-user=$(cat USERNAME) --image-token=$(cat PASSWORD) \
                 --space-username=${{ secrets.SPACE_USERNAME }} --space-password=${{ secrets.SPACE_PASSWORD }} --space-org=${{ secrets.ORG_ID }} \
@@ -124,7 +135,7 @@ jobs:
               else
                 echo "without credentials"
                 space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
-                $commit_sha "$(git rev-parse HEAD)" done \
+                $commit_sha "$(git log --format=%B -1 $commit_sha)" done \
                 $image_url/$name:$commit_sha \
                 --space-username=${{ secrets.SPACE_USERNAME }} --space-password=${{ secrets.SPACE_PASSWORD }} --space-org=${{ secrets.ORG_ID }} \
                 ${{ secrets.API_URL }} || { echo "::warning::Failed to report ${name}" ; errors+=("${name}") ;}
