Changed main and manual pipelines (#5)

diff --git a/.github/workflows/malevich-ci__manual.yml b/.github/workflows/malevich-ci__manual.yml
--- a/.github/workflows/malevich-ci__manual.yml
+++ b/.github/workflows/malevich-ci__manual.yml
@@ -19,20 +19,130 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ github.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/dev' }}
     steps:
+      - name: "Install aws cli"
+        uses: unfor19/install-aws-cli-action@v1
       - name: Checkout
         uses: actions/checkout@v4.1.0
         with:
           ref: ${{ inputs.branch }}
-      - name: Malevich CI Actions
-        uses: MalevichAI/auto-ci@v0.2.0
+      - name: Docker Login
+        run: |
+          if [[ ${{ secrets.REGISTRY_TYPE }} == ecr* ]];
+          then
+            if [[ ${{ secrets.REGISTRY_TYPE}} == 'ecr-private' ]];
+              then
+                image_url=${{ secrets.REGISTRY_ID }}.dkr.ecr.us-east-1.amazonaws.com
+              else
+                image_url=${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_ID }}
+            fi
+            echo 'Log in via AWS CLI'
+            aws configure set aws_access_key_id ${{ secrets.IMAGE_USERNAME }}
+            aws configure set aws_secret_access_key ${{ secrets.IMAGE_PASSWORD }}
+            aws configure set region us-east-1
+            if [[ ${{ secrets.REGISTRY_TYPE}} == 'ecr-private' ]];
+            then
+              token=$(aws ecr get-login-password)
+            else
+              token=$(aws ecr-public get-login-password)
+            fi
+            username=AWS
+          else
+            echo 'Default log in'
+            username=${{ secrets.IMAGE_USERNAME }}
+            token=${{ secrets.IMAGE_PASSWORD }}
+          fi
+          echo "$username" >> USERNAME
+          echo "$token" >> PASSWORD
+          echo $token | docker login --username $username --password-stdin $image_url || \
+          { echo "::error::Failed to log in" ; exit 1 ;}
+        id: docker_login
+      - name: Install python
+        uses: actions/setup-python@v4
         with:
-          registry: ${{ secrets.REGISTRY_TYPE }}
-          registry_url: ${{ secrets.REGISTRY_URL }}
-          registry_id: ${{ secrets.REGISTRY_ID }}
-          username: ${{ secrets.IMAGE_USERNAME }}
-          password: ${{ secrets.IMAGE_PASSWORD }}
-          space_username: ${{ secrets.SPACE_USERNAME }}
-          space_password: ${{ secrets.SPACE_PASSWORD }}
-          api_url: ${{ secrets.API_URL }}
-          org_id: ${{ secrets.SPACE_ORGANIZATION_ID }}
-          build: ${{ inputs.build }}
+          python-version: '3.11'
+      - name: Install Malevich
+        run: |
+          pip install malevich-space>=0.2.3 || { echo "::error::Failed to install malevich" ; exit 1 ;}
+      
+      - name: Get branch name
+        run: echo "branch=$(git branch --show-current)" >> $GITHUB_OUTPUT
+        id: extract_branch
+      
+      - name: Build, Test and Push
+        run: |
+          dirs=$(git log --name-only | grep '/' | cut -d '/' -f3 | sort -u)
+          errors=()
+          commit_sha=$(git rev-parse HEAD)
+          if [[ ${dirs[0]} == "" ]];
+          then
+            echo "No changed directories, exiting..."
+            exit 0
+          fi
+          if [[ ${{ secrets.REGISTRY_TYPE}} == 'ecr-private' ]];
+          then
+            image_url=${{ secrets.REGISTRY_ID }}.dkr.ecr.us-east-1.amazonaws.com
+          else
+            image_url=${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_ID }}
+          fi
+          for dir in $dirs
+          do  
+            dir=lib/src/$dir
+            name=$(basename $dir)
+              if [[ $dir != *.* ]] && [[ -e $dir ]] && [[ -f $dir/Dockerfile ]];
+            then
+              echo "Building ${name}"
+              docker build -q -t $image_url/$name:$commit_sha $dir || { echo "::warning::Failed to build ${name}" ; errors+=("${name}") ; continue ;}
+              if [[ ${{ secrets.REGISTRY_TYPE}} == ecr* ]];
+              then
+                echo "Finding/Creating AWS repository"
+                if [[ ${{ secrets.REGISTRY_TYPE}} == "ecr" ]];
+                then
+                  aws ecr-public describe-repositories --repository-names $name > /dev/null || \
+                  aws ecr-public create-repository --repository-name $name > /dev/null 
+                else
+                  aws ecr describe-repositories --repository-names $name > /dev/null || \
+                  aws ecr create-repository --repository-name $name > /dev/null
+                fi
+              fi  
+              echo "Pushing ${name}"
+              docker push -q --all-tags $image_url/$name || { echo "::warning::Failed to push ${name}" ; errors+=("${name}") ; continue ;}
+              
+              if [[ -f .github/workflows/app.py ]];
+              then
+                python3 .github/workflows/app.py --path "lib/src/${name}/space.yaml" --url "$image_url/$name:$commit_sha"
+              else
+                echo "::warning::${name} has no space.yaml"
+              fi
+
+              echo -n "Testing ${name}"  
+              if [[ ${{ secrets.IMAGE_USERNAME }} == "$(cat USERNAME)" ]] && [[ ${{ secrets.IMAGE_PASSWORD}} == "$(cat PASSWORD)" ]];
+              then
+                echo "with credentials"
+                space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
+                $commit_sha "$(echo $commit_sha | git log --format=%B -n 1)" done \
+                $image_url/$name:$commit_sha \
+                --image-user=$(cat USERNAME) --image-token=$(cat PASSWORD) \
+                --space-username=${{ secrets.SPACE_USERNAME }} --space-password=${{ secrets.SPACE_PASSWORD }} --space-org=${{ secrets.ORG_ID }} \
+                ${{ secrets.API_URL }} || { echo "::warning::Failed to report" ; errors+=("${name}") ;}
+              else
+                echo "without credentials"
+                space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
+                $commit_sha "$(git rev-parse HEAD)" done \
+                $image_url/$name:$commit_sha \
+                --space-username=${{ secrets.SPACE_USERNAME }} --space-password=${{ secrets.SPACE_PASSWORD }} --space-org=${{ secrets.ORG_ID }} \
+                ${{ secrets.API_URL }} || { echo "::warning::Failed to report ${name}" ; errors+=("${name}") ;}
+              fi  
+              echo "Tagging ${name} as latest and pushing"
+              docker tag $image_url/$name:$commit_sha $image_url/$name:latest
+              docker push -q --all-tags $image_url/$name || { echo "::warning::Failed to push ${name} as latest" ; errors+=("${name}") ; continue ;}
+            fi
+          done
+          if [[ ${#errors[@]} > 0 ]];
+          then
+            echo "::error::Failed apps: ${errors[@]}"
+          fi
+
+      - run: |
+          rm USERNAME
+          rm PASSWORD
+          docker logout  
