Update malevich-ci__manual.yml

diff --git a/.github/workflows/malevich-ci__manual.yml b/.github/workflows/malevich-ci__manual.yml
--- a/.github/workflows/malevich-ci__manual.yml
+++ b/.github/workflows/malevich-ci__manual.yml
@@ -61,7 +61,7 @@ jobs:
           python-version: '3.11'
       - name: Install Malevich
         run: |
-          pip install "malevich-space<0.4.13" || { echo "::error::Failed to install malevich" ; exit 1 ;}
+          pip install "malevich-space>=0.4.19" || { echo "::error::Failed to install malevich" ; exit 1 ;}
       
       - name: Get branch name
         run: echo "branch=$(git branch --show-current)" >> $GITHUB_OUTPUT
