fixed manual

diff --git a/.github/workflows/malevich-ci__manual.yml b/.github/workflows/malevich-ci__manual.yml
--- a/.github/workflows/malevich-ci__manual.yml
+++ b/.github/workflows/malevich-ci__manual.yml
@@ -66,7 +66,8 @@ jobs:
           python-version: '3.11'
       - name: Install Malevich
         run: |
-          pip install "malevich-space>=0.4.19" || { echo "::error::Failed to install malevich" ; exit 1 ;}
+          pip install "malevich-space" || { echo "::error::Failed to install malevich_space" ; exit 1 ;}
+          pip install "malevich-coretools" || { echo "::error::Failed to install malevich_coretools" ; exit 1 ;}
       
       - name: Get branch name
         run: echo "branch=$(git branch --show-current)" >> $GITHUB_OUTPUT
@@ -96,9 +97,9 @@ jobs:
           else
             image_url=${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_ID }}
           fi
+          dirs=$( echo $dirs | xargs )
           for dir in $dirs
           do
-            dir=$( echo $dir | xargs )
             dir=lib/src/$dir
             name=$(basename $dir)
             if [[ "$dir" != *.* ]] && [[ -e "$dir" ]] && [[ -f "$dir/Dockerfile" ]]; 
